"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import TopNav from "@/components/nav/TopNav";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [fullScreen, setFullScreen] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app_nav">
          <Nav />
        </div>
        <div
          className={`app_children ${
            fullScreen ? "full_screen" : "half_screen"
          }`}
        >
          <div className="app_top_nav">
            <TopNav setFullScreen={setFullScreen} />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
